language: go

services:
- docker

env:
  global:
  - GO111MODULE=on
  - VERSION="${TRAVIS_TAG:-dev}"
  # latest tag build only from stable, see release.sh
  - TAGS="${VERSION}"
  matrix:
  - GIMME_OS=linux GIMME_ARCH=amd64
  - GIMME_OS=darwin GIMME_ARCH=amd64
  - GIMME_OS=windows GIMME_ARCH=amd64

script:
- set -e
- make
- make test

after_success:
- ./release.sh

before_deploy:
- make package

deploy:
- provider: releases
  api_key: $GITHUB_ACCESS_TOKEN
  overwrite: true
  skip_cleanup: true
  file_glob: true
  file:
  - bin/wodby-*.tar.gz
  on:
    tags: true

- provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: wodby-releases
  upload-dir: wodby-cli/dev
  overwrite: true
  skip_cleanup: true
  local_dir: bin
  on:
    tags: false

- provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: wodby-releases
  upload-dir: wodby-cli/2.0
  overwrite: true
  skip_cleanup: true
  local_dir: bin
  branch: '2.0'
  on:
    tags: false

- provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: wodby-releases
  upload-dir: wodby-cli/${VERSION}
  overwrite: true
  skip_cleanup: true
  local_dir: bin
  on:
    tags: true

- provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: wodby-releases
  upload-dir: wodby-cli/latest
  overwrite: true
  skip_cleanup: true
  local_dir: bin
  on:
    tags: true
